name: philipcornett
favicon: null
layout_spectrum: 0.7347708649467677
typography_spectrum: 0.6748227837961167
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.20576851442456245
  lightness: 0.12447918462567031
  saturation: 0.1775581280235201
  rhythmicContrast: 0.28363414388149977
purpose: []
